### ISSUE TITLE
Error in Console...

### ISSUE THREAD

**Issue by CloudeLecaw** [Benz56/PexTabCompleter#1]
Without a real reason the Console sometimes spams this line
We are using the latest version of PexTabComplter with Paper 1.19 Build 81
```
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: java.net.UnknownHostException: api.spigotmc.org
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/java.net.Socket.connect(Socket.java:633)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at PermissionsEx-TabCompleter_1.3.1.jar//com.benzoft.pextabcompleter.UpdateChecker$1.lambda$run$0(UpdateChecker.java:37)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:36:47] [Craft Scheduler Thread - 295 - PexTabCompleter/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by CloudeLecaw** [comment]
```
[19:14:07 INFO]: Update checker failed!
[19:14:07 WARN]: java.net.UnknownHostException: api.spigotmc.org
[19:14:07 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
[19:14:07 WARN]: 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[19:14:07 WARN]: 	at java.base/java.net.Socket.connect(Socket.java:633)
[19:14:07 WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
[19:14:07 WARN]: 	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[19:14:07 WARN]: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[19:14:07 WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
[19:14:07 WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
[19:14:07 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[19:14:07 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[19:14:07 WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
[19:14:07 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[19:14:07 WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
[19:14:07 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[19:14:07 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[19:14:07 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[19:14:07 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[19:14:07 WARN]: 	at PermissionsEx-TabCompleter_1.3.1.jar//com.benzoft.pextabcompleter.UpdateChecker$1.lambda$run$0(UpdateChecker.java:37)
[19:14:07 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[19:14:07 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:14:07 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:14:07 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:14:07 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:14:07 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by CloudeLecaw** [comment]
Any news about this, or solutions?

**Comment by CloudeLecaw** [comment]
closed because the dev ignores  is since two years
